- label: "Setup"
  message: "Completed"
  color: "green"
- label: "PR Size"
  message: "Large"
  color: "red"
  when: "$additions > 20"
- label: "Missing"
  message: "Important section!"
  color: "#ff0000"
  when: "$payload.pull_request.body.includes('Important section') === false"
