name: staries
channels:
  - conda-forge
  - defaults
dependencies:
  # conda packages
  - papermill=2.0.0
  - jupytext=1.4.1
  - nbdime=2.0.0
  - watermark=2.0.2
  - pip
  - pip:
    # pip libraries
    - cpat
    - zenodo_get
    # for requirements.txt
    - r file: requirements.txt
    # for wheels
    - http://www.lfd.uci.edu/~gohlke/pythonlibs/bofhrmxk/opencv_python-3.1.0-cp35-none-win_amd64.whl
