name: Test comment
on:
  pull_request:
jobs:
  demo-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Test create comment
        with:
          body: |
            This is a multi-line test comment
          reactions: '+1'
