name: add-reviewers

on:
  pull_request_target:
    branches:
      - master
    types:
      - opened
      - edited
    paths:
    - '.docker/*'
    - 'containers'
    - './*'

jobs:
  no-checkout-action:
    strategy:
      matrix:
          reviewer: ["gcpu", "gpcu"]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Add Pull Request Reviewer
      uses: AveryCameronUofR/add-reviewer-gh-action@1.0.3
      with: 
        reviewers: ${{ matrix.reviewer }}
        token: ${{ secrets.GITHUB_TOKEN }}
