# https://betterprogramming.pub/how-to-version-your-code-in-2020-60bdd221278b
name: Bump version in git

on:
  push:
    branches: 
    - master
jobs:
  build-and-deploy:    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Bump version
      run: |
        # https://github.com/actions/checkout/issues/13#issue-481453396
        git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
        git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
        git fetch --tags
        wget -O - https://raw.githubusercontent.com/treeder/bump/master/gitbump.sh | bash
