name: docker
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    paths:
    - '.docker/*'
  push:
    types: [opened, reopened, synchronize, closed]
    branches: 
      - master
      - main
    paths:
    - '.docker/*'
jobs:
  linux:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1.0.1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.0.4
      -
        name: Login to DockerHub
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2.2.1
        with:
          context: ./.docker
          file: ./.docker/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/notebook:latest
