name: docker
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    paths:
    - '.docker/*'
jobs:
  linux:
#     if: contains(github.event.head_commit.message, '[build .docker]') == true
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./.docker
          file: ./.docker/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/notebook:latest
