name: docker
on:
  pull_request:
    types: [opened, edited, reopened, synchronize, closed]
    paths:
    - '.docker/*'
jobs:
  linux:
#     if: contains(github.event.head_commit.message, '[build .docker]') == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.0.1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.0.4
      - name: Login to DockerHub
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to Quay
        uses: docker/login-action@v1.8.0
        with:
          path: .
          registry: quay.io
          username: ${{ secrets.QUAY_REGISTRY_NAMESPACE }}
          password: ${{ secrets.QUAY_REGISTRY_PASSWORD }}
      - name: Build and push to DockerHub
        uses: docker/build-push-action@v2.2.1
        with:
          path: .
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/notebook:latest
            quay.io/${{ secrets.QUAY_REGISTRY_NAMESPACE }}/notebook:latest

