name: docker
on:
  pull_request:
    types: [opened, edited, reopened, synchronize, closed]
    paths:
    - '.docker/*'
jobs:
  linux:
#     if: contains(github.event.head_commit.message, '[build .docker]') == true
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta (tag with git commit hash)
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
        # list of Docker images to use as base name for tags
         images: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/notebook
            quay.io/${{ secrets.QUAY_REGISTRY_NAMESPACE }}/notebook
        # add git short SHA as Docker tag
         tag-sha: true
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_REGISTRY_USERNAME }}
          password: ${{ secrets.QUAY_REGISTRY_PASSWORD }}
      - name: Build and push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .docker/
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/notebook:latest
            quay.io/${{ secrets.QUAY_REGISTRY_NAMESPACE }}/notebook:latest

