name: get-libs
on: push
jobs:
  linux:
    if: contains(github.event.head_commit.message, '[get libs]') == true
    strategy:
      matrix:
        r: [latest]
    runs-on: ubuntu-latest
    container: cgpu/ropensci-rclean@sha256:42465d86c9ed21b7473dcbaf198b5947c76b346658ce8394f9e734395f534043
    steps:
    - uses: actions/checkout@v2
    - name: Run get_libs
      run: |
        Rscript -e "scripts <- list.files('.', pattern = '.R|.Rmd|.ipynb', recursive = TRUE); dput(unique(unlist(lapply(scripts, Rclean::get_libs))))"
      shell:
        bash
