name: lintr
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    paths:
    - '**.R'

jobs:
  linux:
    if: contains(github.event.head_commit.message, '[lint skip]') == false
    runs-on: ubuntu-latest
    container: cgpu/lintr
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Installing processx >= 3.5.0
      run: |
        Rscript -e "Sys.setenv(TAR = '/bin/tar'); options(repos = 'https://cloud.r-project.org/'); install.packages('remotes')"
        Rscript -e "Sys.setenv(TAR = '/bin/tar'); options(repos = 'https://cloud.r-project.org/'); remotes::install_version('processx', version = '>= 3.5.0')"
      shell:
        bash
    - name: Running lintr
      run: |
        Rscript -e "lintr::lint_dir('./Rmdies/R')"
      shell:
        bash
    - name: Setup tmate session
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
